### ISSUE TITLE
Mute/Disable Mic 

### ISSUE THREAD

**Issue by KCastiglione** [jgh-/VideoCore#106]
how to disable / mute mic recording in VCSimpleSession?

is it possible to do it dynamically when session is running?

**Comment by jgh-** [comment]
Set the micGain property to 0

**Comment by KCastiglione** [comment]
i set it to 0 didn't work. set it to 0.000001 and it worked. thanks

**Comment by EVENFATE** [comment]
it still doesnt work to set 0 ,whats the problem?how to solve??

**Comment by havocked** [comment]
Sup'

So what I did in order to work this out was:

in the delegate of VCSimpleSession:
 -(void)didAddCameraSource:(VCSimpleSession *)session

I set the micGain to 1:
[_session setMicGain:1]; //_session is a VCSimpleSession * property in my view

And then I could set it to 0 whenever I wanted to mute de mic:

- (IBAction)muteAction:(id)sender {
    int isEnabled = (int)_session.micGain;
    if (isEnabled == 1) {
        //mute action
        [_session setMicGain:0];
    } else {
        //Unmute action
        [_session setMicGain:1];
    }
}

**Comment by EVENFATE** [comment]
thank u for help.

**Comment by EVENFATE** [comment]
after i connected a rtmp server, i met a error
