### ISSUE TITLE
Port to Android

### ISSUE THREAD

**Issue by abo** [jgh-/VideoCore#134]

**Comment by loretoparisi** [comment]
I see difficult to do a real porting to Android OS due to severe limitations of Android OS encoding API.
Normally you would

- Use ffpmeg embedded, like https://github.com/guardianproject/android-ffmpeg
- Use LAME as encoder unit, http://lame.sourceforge.net/

For my experience, there will be several problems. So I would try another way:

- Port to C++ (I think this is the best option, assumed to have the right experience)
- Port to C# with Xamarin Studio / mono (Xamarin for iOS should have full support for iOS frameworks).
