### ISSUE TITLE
Broadcasting Latency

### ISSUE THREAD

**Issue by redsh** [jgh-/VideoCore#63]
I've run some tests against ffmpeg rtmp upstreams with -tune zerolatency. Is it possible to reduce VideoCore latency/buffer sizes using some settings/flags?

**Comment by RobertSmart** [comment]
Hi, I'm also seeing some latency. I'm trying to figure out where it is coming from. i'm streaming to a wowza server, and if I start to view the stream after I started streaming, the viewed stream starts from the beginning rather than being live (as in the most recent package), I've set wowza to use very small packet sizes, so,it's either the streamer or the video player I think. 

How should I go about testing if video core is causing the lag? In terms of settings, it is pretty much exactly the same as the swift sample code.

Thanks,

Rob

**Comment by jgh-** [comment]
VideoCore has an algorithm to reduce the size of the client-side buffer by reducing the video and audio bitrates.  This shouldn't be a client-side issue.  If it is starting from the beginning of the video it sounds like a settings problem with either your HLS stream (which I assume is what you're talking about) or the player you're playing back with.
